const projects = [
  {
    id: 11,
    image: "/assets/projects/payplate.PNG",
    title: "PayPlate",
    description: "Modern payment platform",
    url: "https://payplate.vercel.app/",
    repo: null, // Closed source
  },
  {
    id: 12,
    image: "/assets/projects/drink-me.PNG",
    title: "Drink Me Splash Zone",
    description: "Interactive beverage experience",
    url: "https://preview--drink-me-splash-zone.lovable.app/",
    repo: "https://github.com/tejasnasre/drink_me",
  },
  {
    id: 1,
    image: "/assets/projects/nexmeet.png",
    title: "nexmeet",
    description: "a open source event platform",
    url: "https://www.nexmeet.social",
    repo: "https://github.com/TejasNasre/nexmeet",
  },
  {
    id: 2,
    image: "/assets/projects/freechatroom.png",
    title: "freechatroom",
    description: "free chat rooms",
    url: "https://freechatroom-three.vercel.app/",
    repo: "https://github.com/TejasNasre/freechatroom",
  },
  {
    id: 3,
    image: "/assets/projects/glitchdrop.png",
    title: "glitchdrop",
    description: "file sharing webapp",
    url: "https://glitchdrop.vercel.app/",
    repo: "https://github.com/soham-khedkar/glitchdrop",
  },
  {
    id: 4,
    image: "/assets/projects/logomaster.png",
    title: "logomaster",
    description: "logo maker and logo editing",
    url: "https://logomaster.vercel.app/",
    repo: "https://github.com/TejasNasre/Logo-Master",
  },
  {
    id: 5,
    image: "/assets/projects/todo.png",
    title: "todozen",
    description: "todo app",
    url: "https://todozen-lovat.vercel.app/",
    repo: "https://github.com/TejasNasre/Todo_App",
  },
  {
    id: 6,
    image: "/assets/projects/game-grid.png",
    title: "game grid",
    description: "game listing",
    url: "https://game-grid-phi.vercel.app/",
    repo: "https://github.com/TejasNasre/Game-Grid",
  },
  {
    id: 13,
    image: "/assets/projects/pdf-rag.png",
    title: "PDF RAG System",
    description: "PDF document retrieval and generation",
    url: "https://pdf-rag-demo.vercel.app/",
    repo: "https://github.com/tejasnasre/pdf-rag",
  },
  {
    id: 7,
    image: "/assets/projects/next-carbon.png",
    title: "next carbon",
    description: "carbon credit marketplace",
    url: "https://nextc-template-y6dy.vercel.app/",
    repo: "https://github.com/Nextc1/nextc_template",
  },
  {
    id: 8,
    image: "/assets/projects/carra.png",
    title: "cara",
    description: "ecommerce website ui",
    url: "https://tejasnasre.github.io/Cara-EcommerceWebsite/",
    repo: "https://github.com/TejasNasre/Cara-EcommerceWebsite",
  },
  {
    id: 9,
    image: "/assets/projects/qr-code.png",
    title: "qr-code",
    description: "simple qr code generator",
    url: "https://tejasnasre.github.io/qrcodeGenerator/",
    repo: "https://github.com/TejasNasre/qrcodeGenerator",
  },
  {
    id: 10,
    image: "/assets/projects/rps.png",
    title: "rock paper scissor",
    description: "simple game",
    url: "https://tejasnasre.github.io/RPS-Game/",
    repo: "https://github.com/TejasNasre/RPS-Game",
  },
];

export default projects;
