const projects = [
  {
    id: 1,
    image: "/src/assets/projects/nexmeet.PNG",
    title: "nexmeet",
    description: "a open source event platform",
    url: "https://www.nexmeet.social",
    repo: "https://github.com/TejasNasre/nexmeet",
  },
  {
    id: 2,
    image: "/src/assets/projects/freechatroom.PNG",
    title: "freechatroom",
    description: "free chat rooms",
    url: "https://freechatroom-three.vercel.app/",
    repo: "https://github.com/TejasNasre/freechatroom",
  },
  {
    id: 3,
    image: "/src/assets/projects/glitchdrop.PNG",
    title: "glitchdrop",
    description: "file sharing webapp",
    url: "https://glitchdrop.vercel.app/",
    repo: "https://github.com/soham-khedkar/glitchdrop",
  },
  {
    id: 4,
    image: "/src/assets/projects/logomaster.PNG",
    title: "logomaster",
    description: "logo maker and logo editing",
    url: "https://logomaster.vercel.app/",
    repo: "https://github.com/TejasNasre/Logo-Master",
  },
  {
    id: 5,
    image: "/src/assets/projects/todo.PNG",
    title: "todozen",
    description: "todo app",
    url: "https://todozen-lovat.vercel.app/",
    repo: "https://github.com/TejasNasre/Todo_App",
  },
  {
    id: 6,
    image: "/src/assets/projects/game grid.PNG",
    title: "game grid",
    description: "game listing",
    url: "https://game-grid-phi.vercel.app/",
    repo: "https://github.com/TejasNasre/Game-Grid",
  },
  {
    id: 7,
    image: "/src/assets/projects/next carbon.PNG",
    title: "next carbon",
    description: "carbon credit marketplace",
    url: "https://nextc-template-y6dy.vercel.app/",
    repo: "https://github.com/Nextc1/nextc_template",
  },
  {
    id: 8,
    image: "/src/assets/projects/carra.PNG",
    title: "cara",
    description: "ecommerce website ui",
    url: "https://tejasnasre.github.io/Cara-EcommerceWebsite/",
    repo: "https://github.com/TejasNasre/Cara-EcommerceWebsite",
  },
  {
    id: 9,
    image: "/src/assets/projects/qr-code.PNG",
    title: "qr-code",
    description: "simple qr code generator",
    url: "https://tejasnasre.github.io/qrcodeGenerator/",
    repo: "https://github.com/TejasNasre/qrcodeGenerator",
  },
  {
    id: 10,
    image: "/src/assets/projects/rps.PNG",
    title: "rock paper scissor",
    description: "simple game",
    url: "https://tejasnasre.github.io/RPS-Game/",
    repo: "https://github.com/TejasNasre/RPS-Game",
  },
];

export default projects;
